### ISSUE TITLE
ViT: 질문 및 further research

### ISSUE THREAD

**Issue by leahincom** [yskim0/CS-Paper-Review#3]
> 하지만 pre-trained position embedding이 의미 없어질 수 있음

input image에 fitting된 결과라서 그런가?

> Transformer는 CNN과 다르게 translation equivariance, locality 같은 inductive biases(=weight sharing)이 없기 때문에 데이터셋이 적으면 generalize되기 어려움

image generation을 통해 해결해보는 건 어떨까?

일단 다양한 분야에 적용시켜 볼 수 있겠다.  classification에 더해서 일단 여기서 언급한 image resolution도 그렇고.   
그리고 patch에서 sequence를 추출한다는게 image reconstruction이랑 비슷한 맥락인 것 같아. 그런 의미에서 image reconstruction에서 position embedding이 input specific한 정보라서 얘를 보완해서 나온 method가 내가 리뷰한 논문이거든? 비슷한 관점에서 ViT가 가진 한계점을 보완할 수 있지 않을까?   
암튼 재밌는 연구다.!!

**Comment by yskim0** [comment]
1. 
> 하지만 pre-trained position embedding이 의미 없어질 수 있음
>> input image에 fitting된 결과라서 그런가?

pre-trained에 적용된 sequence length에 position embedding이 fitting 됐다는 말이면 맞아. 
sequence length를 pre-trained 에서 사용했던 시퀀스 길이와 다른 걸 쓴다면, **position embedding 해야하는 길이도 달라지니까** 의미가 없어진다는 뜻! 

2.
>Transformer는 CNN과 다르게 translation equivariance, locality 같은 inductive biases(=weight sharing)이 없기 때문에 데이터셋이 적으면 generalize되기 어려움
>> image generation을 통해 해결해보는 건 어떨까?

이미지 제너레이션이 이미 있는 이미지에서 새로운 샘플들을 만들어내는 건가? 잘 모르겠어서 이게 맞는지 확인 부탁함!
근데 이게 비단 학습에 들어가는 데이터의 문제는 아니고 Transformer 자체가 CNN과 달리 GLOBAL 하게 본다는 특성이 작용하는 듯... 둘의 장단점이 뚜렷이 보이는 지점이랄까.. DETR에서도 이런 특성때문에 small object를 디텍션 하는데 있어서 Fast R-CNN 보다 성능이 모자랐거든. 근데 또 ㅋㅋㅋㅋ 갓 나온 논문인데 `Deformable DETR`에서 이를 극복했대. 다음엔 이건 읽어보려고 해!~

일단 이 연구분야가 가진 의의는 우리가 해야할 과제들이 많다는 것? 전망이 좋다 볼 수 있지... image detection, segmentation 기존 연구들 보면 사실 현실에서는  연구에서의 성능만큼 안나오잖아. 그 이유가  그게 이미지를 전체 맥락적으로? global하게, contextful 하게 못 봐서 그렇다고 생각해. (다른 연구자들도 그렇게 많이 생각할 걸!?) 실제 사용되기 위해서 해결해야 하는 문제점을 이거로 극복하려는 듯.
근데 또 갓 나온 연구니까 바로 현실 적용시키기에는 많은 연구가 필요하고!! 완전 ***금광산*** 아니냐구~~!

> 그리고 patch에서 sequence를 추출한다는게 image reconstruction이랑 비슷한 맥락인 것 같아. 그런 의미에서 image reconstruction에서 position embedding이 input specific한 정보라서 얘를 보완해서 나온 method가 내가 리뷰한 논문이거든? 비슷한 관점에서 ViT가 가진 한계점을 보완할 수 있지 않을까?
암튼 재밌는 연구다.!!

이미지 reconstruction에 대해서 내가 잘 몰라서 확신은 안들지만, 너 얘기 듣고나서는 진짜 서로 사용할 수도 있을 것 같다 ㅋㅋ 또 반대로 image reconstruction task를 할 때 ViT나 DETR등 기존의 CNN 기반의 모델을 썼다면, 이제 트랜스포머 기반의 모델을 사용했을 때의 다른 이점, 차별점을 얻을 수 있지 않을까?
