### ISSUE TITLE
Unsupervised Intra-domain Adaptation for Semantic Segmentation 리뷰

### ISSUE THREAD

**Issue by yskim0** [yskim0/CS-Paper-Review#4]
DA는 처음이라, 너 리뷰 보면서 이해하고 정리 하면서 읽었어. 기울임체는 질문이 아니라 내가 이해한대로  정리한 거니까 맞다면 그냥 넘어가고, 틀리면 지적해줘 ㅋㅋ 

## Introduction
> Synthetic data 

- 여기서 말하는 **Synthetic data가 위에서 언급한 시뮬레이터나 게임 엔진에서 나온 데이터**지??
그래서 리얼 데이터랑 다른 지점이 있다는 거고...
- 암튼 synthetic data를 획득해서 **원하는 도메인에 real data와 domain-difference 와 거의 차이없게 하는 게 domain adaptation 맞아?**

> Source Domain vs. Target Domain

_여기서 `source domain` : GTA, simulation ,
`target domain` : real data 이다._

> Inter-domain vs. Intra-domain

_Inter-domain : Target-Source 간의 Gap_
_Intra-domain : Target 내부의 domain gap_
- _Target domain은  Hard, Easy로 나눌 수 있고_
- _easy, hard 사이의 gap을 줄이는 것이 목표다._

> Model

어느정도는 이해한 듯

---

이 연구가 Oral로 선정된 이유는 기존 DA 연구들은 inter-domain에 집중했는데 여기서는 intra-domain을 집중적으로 조명해서 성능향상을 이끌었기 때문인가? 점점 딥러닝이 발전하면서 데이터셋의 부족하다든지, 너무 비용이 비싸서 만들기도 힘들다든지 그렇다는데
그래서 도메인 adaptation도 유망한 부분인 것 같아 ㅋㅋ GTA나 시뮬레이션으로도 좋은 데이터를 많이 만들게 될 수 있으니...
재밌는 연구네 👍

**Comment by leahincom** [comment]
> 1. 여기서 말하는 Synthetic data가 위에서 언급한 시뮬레이터나 게임 엔진에서 나온 데이터지??
> 그래서 리얼 데이터랑 다른 지점이 있다는 거고...
> 2. 암튼 synthetic data를 획득해서 원하는 도메인에 real data와 domain-difference 와 거의 차이없게 하는 게 domain adaptation 맞아?

1,2 둘 다 ㅇㅇ!!

> 점점 딥러닝이 발전하면서 데이터셋의 부족하다든지, 너무 비용이 비싸서 만들기도 힘들다든지 그렇다는데
> 그래서 도메인 adaptation도 유망한 부분인 것 같아 ㅋㅋ GTA나 시뮬레이션으로도 좋은 데이터를 많이 만들게 될 수 있으니...

이게 포인트임!! dataset이 부족해서 small dataset을 한계점으로 잡는 연구가 많잖아. 이걸 image generation을 통해서 해결할 수 있는데 domain이 달라서 training과 별개로 method가 real data에 적용되지 않는 문제가 있으니 domain adaptation을 이용해서 해결. 이 방법은 이 adaptation의 정확도를 향상시키기 위해서 다른 관점에서 문제를 보고 해결했다는게 매력적인 듯!

**Comment by yskim0** [comment]
오호... 이것도 돈이 좀 될 듯한 연구군^^
